baseURL = "/"
canonifyURLs = false
relativeURLs = true
languageCode = "en-us"
title = ""
theme = "blowfish"
[params]
colorScheme = "slate"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
