baseURL = "https://BryanG-Dev.github.io/my_portfolio/"
languageCode = "en-us"
title = ""
theme = "blowfish"
[params]
colorScheme = "grey"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
